server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /book-api

spring:
  datasource:
    # 华为云RDS数据库的内网地址
    url: jdbc:mysql://192.168.249.147:3306/wisebookpal?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    # 华为云RDS数据库的密码
    password: aA123456bookpal
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 3000

  sql:
    init:
      encoding: utf8
      schema-locations: classpath:mysql_init.sql
      mode: never
      separator: ;

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Shanghai

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.whu.bookapi: DEBUG
    com.zaxxer.hikari: DEBUG

app:
  files:
    upload-dir: ./uploads