server:
  port: 8080
  servlet:
    context-path: /book-api
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:mysql://localhost:3306/wisebookpal?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:mysql_init.sql
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
app:
  files:
    upload-dir: ./uploads
